// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Soft delete by marking is_active = false
	DeleteUrlByCode(ctx context.Context, arg DeleteUrlByCodeParams) error
	GetActiveUrlByCode(ctx context.Context, shortCode string) (Url, error)
	GetNextSequenceVal(ctx context.Context) (int64, error)
	GetUrlByCode(ctx context.Context, shortCode string) (Url, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	ListUrlsByUserId(ctx context.Context, userID int64) ([]Url, error)
	UpdateUrlIsActive(ctx context.Context, arg UpdateUrlIsActiveParams) error
}

var _ Querier = (*Queries)(nil)
