// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (short_code, original_url, user_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, short_code, original_url, user_id, is_active, expires_at, created_at, updated_at
`

type CreateUrlParams struct {
	ShortCode   string             `json:"short_code"`
	OriginalUrl string             `json:"original_url"`
	UserID      int64              `json:"user_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, createUrl,
		arg.ShortCode,
		arg.OriginalUrl,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUrlByCode = `-- name: DeleteUrlByCode :exec
UPDATE urls
SET is_active = FALSE, updated_at = NOW()
WHERE short_code = $1 AND user_id = $2
`

type DeleteUrlByCodeParams struct {
	ShortCode string `json:"short_code"`
	UserID    int64  `json:"user_id"`
}

// Soft delete by marking is_active = false
func (q *Queries) DeleteUrlByCode(ctx context.Context, arg DeleteUrlByCodeParams) error {
	_, err := q.db.Exec(ctx, deleteUrlByCode, arg.ShortCode, arg.UserID)
	return err
}

const getActiveUrlByCode = `-- name: GetActiveUrlByCode :one
SELECT id, short_code, original_url, user_id, is_active, expires_at, created_at, updated_at FROM urls
WHERE short_code = $1 AND is_active = TRUE AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

func (q *Queries) GetActiveUrlByCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getActiveUrlByCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextSequenceVal = `-- name: GetNextSequenceVal :one
SELECT nextval('url_code_seq')
`

func (q *Queries) GetNextSequenceVal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getNextSequenceVal)
	var nextval int64
	err := row.Scan(&nextval)
	return nextval, err
}

const getUrlByCode = `-- name: GetUrlByCode :one
SELECT id, short_code, original_url, user_id, is_active, expires_at, created_at, updated_at FROM urls
WHERE short_code = $1 LIMIT 1
`

func (q *Queries) GetUrlByCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getUrlByCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUrlsByUserId = `-- name: ListUrlsByUserId :many
SELECT id, short_code, original_url, user_id, is_active, expires_at, created_at, updated_at FROM urls
WHERE user_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListUrlsByUserId(ctx context.Context, userID int64) ([]Url, error) {
	rows, err := q.db.Query(ctx, listUrlsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.UserID,
			&i.IsActive,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUrlIsActive = `-- name: UpdateUrlIsActive :exec
UPDATE urls
SET is_active = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUrlIsActiveParams struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) UpdateUrlIsActive(ctx context.Context, arg UpdateUrlIsActiveParams) error {
	_, err := q.db.Exec(ctx, updateUrlIsActive, arg.ID, arg.IsActive)
	return err
}
